### ISSUE TITLE
Callout text

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system-backlog#123]
AKA: Highlight text, Inset text

## What
Draw attention to or visually distinguish text on a page:

![image](https://user-images.githubusercontent.com/1590604/36040552-b3e10768-0dbd-11e8-9019-a14c2d935b57.png)

## Why
We had planned to deprecate this component as there was confusion over it's appropriate use. However, during user research participants brought many examples of pages using this component, so it feels like we should review again.

## Anything else

**Comment by joelanman** [comment]
[Interesting thread on Twitter about this](https://twitter.com/joelanman/status/941285632881463296)

One of the points there is that content in this pattern is sometimes ignored because it looks like a quote from the main body of text. Therefore users assume its not important to read the quote - they will come across it in the main body.

**Comment by nickcolley** [comment]
can we close this in favour of https://github.com/alphagov/govuk-design-system-backlog/issues/136 ?
