### ISSUE TITLE
Add GOV.UK Mural template to community resources 

### ISSUE THREAD

**Issue by vickytnz** [alphagov/govuk-design-system-backlog#250]
## What
Way for people to make Mural wireframes

## Why
People in various government departments aren't allowed to use Figma but can use Mural. This helps them wireframe it.

## Anything else
https://github.com/vickytnz/govuk-elements-mural includes notes on how to use and support. (I have a Miro one as well but need to update that first).

**Comment by CharlotteDowns** [comment]
You can now create [GOV.UK Design System Flow Diagrams for Mural](https://github.com/clare-brown/govuk-designsystem-flow-diagram-mural). 

This was added in August 2022 as part of the [add in link to Mural file pull request](https://github.com/alphagov/govuk-design-system/pull/2318) and also relates to [this similar contribution](https://github.com/alphagov/govuk-design-system/pull/2281)

**Comment by tomyems** [comment]
@CharlotteDowns The issue was about the [GOV.UK elements mural](https://github.com/vickytnz/govuk-elements-mural) which is used for wireframes rather than the flow diagram. It would be listed under 'Create prototypes and wireframes' rather than 'Create flow diagrams'. Please could you reconsider adding this to the resources and tools section, as it's super useful?

**Comment by CharlotteDowns** [comment]
@tomyems @vickytnz that should be in the list now too
