### ISSUE TITLE
Ethnicity / Background Questions

### ISSUE THREAD

**Issue by GaryCullenDev** [alphagov/govuk-design-system-backlog#274]
We have used the GDS pattern for asking people about ethnicity and subsequently background. We have received feedback from a person who identifies as Roma that when a user selects "white" and the options provided include "Gypsy or Irish Traveller" it can be considered offensive. The literature online suggests there is a divide within the community as to those who find the term offensive and those who embrace it as part of their heritage. 

Should the options therefore be:
- English, Welsh, Scottish, Northern Irish or British
- Irish
- Irish Traveller
- Roma
- Any other White background

Where selecting other prompts a free type field for those who would like to use the term themselves?

**Comment by querkmachine** [comment]
Hi Gary,

The questions, answers and the wording we use for the equality information pattern originates from the Government Statistical Service's harmonisation standard, which aims to make these kinds of questions consistent across central and devolved governments, questionnaires, and the Census. 

You can see the GSS standard for ethnicity-related questions here: https://analysisfunction.civilservice.gov.uk/policy-store/ethnicity-harmonised-standard/

Part of the reason for this enforced consistency is so that direct comparisons can be made between data collected from different methods and at different times. I don't think we would be comfortable changing our guidance without the GSS standard being updated first. 

As such, I'm going to close this issue. Feel free to leave any other comments on the pattern in the equality information issue:
- #180

Thanks!
