### ISSUE TITLE
When should Error message clear after correct data entered

### ISSUE THREAD

**Issue by jane-wallis3** [alphagov/govuk-design-system-backlog#297]
## What
> When a user has received an error message after entering incorrect data in a system field, and then they enter the correct data, should the error message disappear as soon as the correct data is entered to indicate to the user they have now entered the correct data? 

## Why
> Logically and from an Accessibility perspective, if the error message doesn't clear immediately then the user may think they have still got something wrong. 
>
> - What evidence do you have that it's needed by multiple services across government? - this seems to be how other GOv.uk sites work too. 
> - What evidence do you have that it meets the needs of the users of those services? - none. this is about the logic of not telling a user they have now entered the information correctly, rather than erroring over and over again. E.g. if they enter half a date of birth in the passport application, they then get told again to enter a complete date of birth. If they cannot see what they have entered as they are visually impaired how can they fix it? 
> - Have you checked that it doesn't already exist in the GOV.UK Design System? - Yes I cannot find this guidance anywhere and several services behave like this. 

## Anything else
> Include links to any examples, research or code to support your proposal, if available. used the date of birth pageas an example https://www.passport.service.gov.uk/filter/age

**Comment by querkmachine** [comment]
This is covered in our guidance on [helping users recover from validation errors](https://design-system.service.gov.uk/patterns/validation/), particularly the 'When to tell users about validation errors' section:

> Do not validate when the user moves away from a field. Wait until they try to move to the next part of the service - usually by clicking the ‘continue’ or ‘submit’ button at the bottom of the page.
> 
> Generally speaking, avoid validating the information in a field before the user has finished entering it. This sort of validation can cause problems - especially for users who type more slowly.

And the 'Client side and server side validation' section:

> Only add client side validation if you find a user need for it. For example, because research shows it helps the user if you validate the information they’re providing as they type.
> 
> Before you add client side validation, consider that:
> 
> * it’s hard to tell the user about errors in a way that works reliably across different browsers and assistive technologies
> * carrying out both kinds of validation means you have to check their rules do not conflict

---

Generally, we advise against against doing 'live' validation for a few reasons:

1. If error messages disappear asynchronously when a value is valid, it stands to reason that error messages must also appear asynchronously when it is invalid. This can create situations where error messages are constantly appearing and disappearing as a user is typing, causing the layout of the page to jump around and creating spam for screen reader users.
2. Alternatively, if validation is only performed when the user moves away from the field, this can frustrate a user as validation errors only appear after they have 'moved on'.
3. Doing this form of live validation necessitates implementing a client-side validation method. Because client-side validation is unreliable, you must also have server-side validation anyway. Implementing client-side validation is therefore surplus to requirements and arguably unnecessary development effort.
4. Some things just cannot be validated as easily using client-side methods than server-side ones. This can create differences in functionality between the two validation methods, also potentially adding to user frustration (e.g. client-side validation marks something as valid but server-side validation doesn't). 
5. Our guidance for validation includes numerous other features other than the error messages themselves, such as changing the page's title and providing an error summary at the top of the page. These add additional complexity to performing live forms of validation, as a user would expect these to update in real time too.

Adam Silver has a good blog post that goes into some of the issues around live validation, with real examples: https://adamsilver.io/blog/the-problem-with-live-validation-and-what-to-do-instead/
